#!/bin/bash
# Remove custom agents from OpenClaw
# Keeps: Shadowman, secrets
# Removes: Agent cron jobs, workspace files, reverts config to shadowman-only
#
# Usage:
#   ./remove-custom-agents.sh
#
# Reads OPENCLAW_NAMESPACE and OPENCLAW_PREFIX from .env (generated by setup.sh)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Load config from .env
if [ -f "$REPO_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
  set +a
else
  echo "ERROR: No .env file found at $REPO_ROOT/.env"
  echo "Run setup.sh first, or set OPENCLAW_NAMESPACE and OPENCLAW_PREFIX manually."
  exit 1
fi

# Validate required vars
if [ -z "$OPENCLAW_NAMESPACE" ]; then
  echo "ERROR: OPENCLAW_NAMESPACE not set in .env"
  exit 1
fi

# Determine agent names (prefixed if OPENCLAW_PREFIX is set)
if [ -n "$OPENCLAW_PREFIX" ]; then
  RESOURCE_OPTIMIZER_ID="${OPENCLAW_PREFIX}_resource_optimizer"
else
  RESOURCE_OPTIMIZER_ID="resource_optimizer"
fi

echo "Removing custom agents from OpenClaw..."
echo "  Namespace: $OPENCLAW_NAMESPACE"
if [ -n "$OPENCLAW_PREFIX" ]; then
  echo "  Prefix:    $OPENCLAW_PREFIX"
fi
echo ""

# Get running pod (exclude job pods)
echo "1. Finding OpenClaw deployment pod..."
POD=$(oc get pods -n "$OPENCLAW_NAMESPACE" -l app=openclaw --field-selector=status.phase=Running -o json | \
  jq -r '.items[] | select(.metadata.ownerReferences[0].kind=="ReplicaSet") | .metadata.name' | head -1)
if [ -z "$POD" ]; then
  echo "   WARNING: No OpenClaw deployment pod found — skipping cron/workspace cleanup"
  echo "   (Pod may not be running; config and restart will still be applied)"
  SKIP_POD=true
else
  echo "   Found: $POD"
  SKIP_POD=false
fi
echo ""

# Remove cron jobs
if [ "$SKIP_POD" = "false" ]; then
  echo "2. Removing cron jobs..."
  oc exec -n "$OPENCLAW_NAMESPACE" "$POD" -c gateway -- bash -c "
    cd /home/node
    if [ -f ~/.openclaw/cron/jobs.json ]; then
      echo '{\"version\":1,\"jobs\":[]}' > ~/.openclaw/cron/jobs.json
      echo '   All cron jobs cleared'
    fi
  "
  echo "   Done"
  echo ""

  # Remove agent workspace directories
  echo "3. Removing agent workspace directories..."
  oc exec -n "$OPENCLAW_NAMESPACE" "$POD" -c gateway -- sh -c "
    for dir in \
      ~/.openclaw/workspace-${RESOURCE_OPTIMIZER_ID} \
      ~/.openclaw/workspace-resource-optimizer; do
      if [ -d \"\$dir\" ]; then
        echo \"   - Removing \$(basename \$dir)...\"
        rm -rf \"\$dir\"
      fi
    done
  "
  echo "   Done"
  echo ""
else
  echo "2. Skipping cron job removal (no pod)"
  echo "3. Skipping workspace removal (no pod)"
  echo ""
fi

# Apply base config (shadowman only)
echo "4. Applying base config (shadowman only)..."
sed "s/namespace: openclaw/namespace: $OPENCLAW_NAMESPACE/g" "$SCRIPT_DIR/../base/openclaw-config-configmap.yaml" | oc apply -f -
echo "   Config updated to shadowman only"
echo ""

# Restart deployment
echo "5. Restarting OpenClaw deployment..."
oc rollout restart deployment/openclaw -n "$OPENCLAW_NAMESPACE"
echo "   Deployment restarting"
echo ""

echo "Done!"
echo ""
echo "Remaining:"
echo "  - Shadowman agent (active)"
echo "  - Agent K8s secrets (kept for future use)"
echo ""
echo "Removed:"
echo "  - Agent workspace directories"
echo "  - Cron jobs"
echo "  - Config reverted to shadowman-only"
echo ""
echo "To re-add agents, re-run setup-agents.sh"
