# Secret: openclaw-secrets
# SECURITY: Generate random secrets before deploying to production
# Generate token: openssl rand -base64 32
# Or use: kubectl create secret generic openclaw-secrets --from-literal=OPENCLAW_GATEWAY_TOKEN="$(openssl rand -base64 32)" --dry-run=client -o yaml
apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secrets
  namespace: openclaw
  labels:
    app: openclaw
  annotations:
    # Rotate secrets regularly (recommendation: every 90 days)
    security.openclaw.ai/last-rotation: "YYYY-MM-DD"
type: Opaque
stringData:
  # REQUIRED: Generate with: openssl rand -base64 32
  OPENCLAW_GATEWAY_TOKEN: "CHANGEME-USE-openssl-rand-base64-32"

  # OTEL collector endpoint (sidecar on localhost)
  OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318

  # MLflow tracking URI (in-cluster service)
  MLFLOW_TRACKING_URI: http://mlflow-service.mlflow.svc.cluster.local:5000

  # Langfuse observability (optional - leave empty if not using)
  LANGFUSE_HOST: ""
  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_SECRET_KEY: ""
